# Generated by Django 3.1.6 on 2022-02-09 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('first_joined', models.DateTimeField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('auth_source', models.CharField(choices=[('google.com', 'Google'), ('facebook.com', 'Facebook'), ('apple.com', 'Apple'), ('password', 'Email')], max_length=20)),
                ('is_info_complete', models.BooleanField(default=False)),
                ('marketing_check', models.BooleanField(default=False)),
            ],
        ),
    ]
