# Generated by Django 3.1.6 on 2022-02-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appconfig', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
    ]
