# Generated by Django 3.1.6 on 2022-03-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0002_labtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='test_date',
            field=models.DateTimeField(),
        ),
    ]
