# Generated by Django 3.1.6 on 2022-03-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0005_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
