# Generated by Django 3.1.6 on 2022-03-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0007_auto_20220321_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='url',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
    ]
