# Generated by Django 3.1.6 on 2022-03-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0008_auto_20220328_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='result_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
