# Generated by Django 3.1.6 on 2022-04-04 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0009_auto_20220329_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='verify_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
