# Generated by Django 3.1.6 on 2022-04-04 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0010_labtest_verify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='verify_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
