# Generated by Django 3.1.6 on 2022-04-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0011_auto_20220404_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
