# Generated by Django 3.1.6 on 2022-05-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0012_labtest_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='attended',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
