# Generated by Django 3.1.6 on 2022-05-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
