# Generated by Django 3.1.6 on 2022-05-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0002_notif_canceled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notif',
            old_name='canceled',
            new_name='read',
        ),
    ]
